### ISSUE TITLE
Rename repo and publish to read-the-docs

### ISSUE THREAD

**Issue by alexgibson** [mozilla/ee-consultant-guidelines#11]
I've moved this repo from the /mozilla/ org to /mozmeao/.

Suggested next steps:

- [x] Rename the repo from `ee-consultant-guidelines` to `consultant-guidelines`.
- [x] Update the readme to reflect the name change.
- [x] Publish the new repo to read-the-docs.

I can take care of the first 2 items easily enough, but I seem to have lost admin access after moving it. Can someone add me?

As for publishing to read-the-docs, do we have a specific account for this already? Not sure what the common procedure is.

/cc @bensternthal

**Comment by bensternthal** [comment]
I think this is all sorted. Unfortunately it looks like we cant change the RTD url. That might be possible if we delete and recreate the project.

**Comment by alexgibson** [comment]
> Unfortunately it looks like we cant change the RTD url

Hmm, so this repo is still publishing to that old RTD url even after we moved orgs? Is it much work to recreate?

**Comment by bensternthal** [comment]
Yep the integration with RTD was preserved through the move. I would be ok deleting this from RTD and starting fresh with a shorter more appropriate URL. This type of documentation.. I suspect is not linked too like other docs would be. 

Alternatively we could use github pages for this and not reply on RTD at all.

**Comment by alexgibson** [comment]
I don't have any strong preference over RTD or GitHub pages, but using the RTD does at least help support their project (which I think is a good one).

**Comment by bensternthal** [comment]
I don't have a strong preference either. We can leave as is.

**Comment by alexgibson** [comment]
Ok, closing 👍
